### PR TITLE
Update YamilovsSypexGeoExtension.php

### PR DESCRIPTION
**Pull request by satmaelstorm**
There is an issue with the types in PHP 7.1. The constant in the config file is a string. I've fixed this issue.

### CODE REVIEW

**Comment by yamilovs** [comment]
Can you describe an issue? Im using this bundle on project with php 7.1 too, and havn't find any issues with config types

**Comment by satmaelstorm** [comment]
With strict mode we have "non integer value". In any case - there is expected int value, but get string.

**Comment by yamilovs** [comment]
Yes i see. You are right. it must be an integer. Give me some time for thinkig about it =)

**Comment by yamilovs** [comment]
@satmaelstorm, can u check this feature - https://github.com/yamilovs/SypexGeoBundle/tree/release/1.2.1
is it ok now for your project?

For integer fix - https://github.com/yamilovs/SypexGeoBundle/commit/6ebb31bb3d6564d91e43aa9c6885cf5f4855a429
Other typos - https://github.com/yamilovs/SypexGeoBundle/commit/85ecf7d4948739a47bb3d6c120ff1894cbe76deb

**Comment by satmaelstorm** [comment]
IMHO, Reflection is the best way, but it is also possible to solve this issue. What about the second commit?

**Comment by yamilovs** [comment]
Reflection class working with all constans and its unnecessary.

And about second commit, i've wrote it above:

> Why are you using file_locator again?
> I removed it in 4574f4c
> Look at database_path here https://github.com/yamilovs/SypexGeoBundle/blob/master/README.md#step-3-add-some-configurations. It's now use kernel.root_dir variable for correct file path.

**Comment by yamilovs** [comment]
@satmaelstorm i released new vercion https://github.com/yamilovs/SypexGeoBundle/releases/tag/1.2.1
If it's ok for you, ill close this pull request. Thx.

**Comment by satmaelstorm** [comment]
Oh no. Production enveronment falls with
InvalidArgumentException in Kernel.php line 214: A resource name must start with @ (".../app/../src/AppBundle/SypexGeoDatabase/SxGeoCity.dat" given).

**Comment by yamilovs** [comment]
@satmaelstorm it's realy strange. i have this configuration on my projects:

```
yamilovs_sypex_geo:
    mode: SXGEO_FILE # SXGEO_FILE (default) | SXGEO_BATCH | SXGEO_MEMORY
    database_path: "%kernel.root_dir%/../var/SypexGeoDatabase/SxGeoCity.dat"
```
And it's work fine.

**Comment by satmaelstorm** [comment]
try 
`database_path: '%kernel.root_dir%/../src/AppBundle/SypexGeoDatabase/SxGeoCity.dat'`
with Symfony 3.1.10

**Comment by yamilovs** [comment]
3.2.3 is all ok
dump http://joxi.net/Q2K44pYcBMP0Aj
controller http://joxi.net/BA0OOp0cEd3n2y
configuration http://joxi.net/Vrwnnq8i6wEZAX

maybe you need to run `composer update yamilovs/sypex-geo-bundle` ?

**Pull request closed without merging**
