### PR TITLE
Proxy Configuration

### PR DESCRIPTION
**Pull request by satmaelstorm**
Added configuration option for proxy

### CODE REVIEW

**Comment by yamilovs** [comment]
Hello! Thanks for your PR. I'll check it soon

**Comment by yamilovs** [comment]
@satmaelstorm can u check my changes? if it's ok, then i'll merge it =)

**Comment by satmaelstorm** [comment]
What is needed is an option http, there is no option https, I also got this from the beginning. Well base64_encoding also required for authorization.

**Comment by yamilovs** [comment]
ok, i just change variable name. Does it working properly?
on my projects, without `connection` configuration, all is ok

**Comment by satmaelstorm** [comment]
All is ok with connection settings too

**Comment by yamilovs** [comment]
Thanks! Tagged as version 1.1.0

**Pull request merged**
